<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">User Stats</h3>
			</div>
			<div class="panel-body">Panel content</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Candle Stats</h3>
			</div>
			<div class="panel-body">Panel content</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Post Stats</h3>
			</div>
			<div class="panel-body">Panel content</div>
		</div>
	</div>
</div>

