<div class="col-md-4">
	<form
		action="<?php echo $this->url("application/child",array("controller"=>"signin","action"=>"process"))?>"
		method="post">
		<div class="form-group">
			Username/Email <br> <input type="text" required class="form-control" id="username"
				name="username" placeholder="Enter username">
		</div>
		<div class="form-group">
			Password <br> <input required type="password" class="form-control"
				id="password" name="password" placeholder="Password">
		</div>
		<div class="checkbox">
			<label> <input name="remember_me" type="checkbox"> Remember Me
			</label>
		</div>
		<button type="submit" class="btn btn-default">Submit</button>
	</form>
</div>