<div class="">
	<div class="col-md-12">
		<div class="panel panel-default">
			<!-- Default panel contents -->
			<div class="panel-heading">Users</div>

			<!-- Table -->
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Username</th>
						<th>First Name</th>
						<th>Last Name</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Mark</td>
						<td>Otto</td>
						<td>mdo</td>
						<td><a href="" class="btn btn-sm btn-default">Edit</a> <a href=""
							class="btn btn-sm btn-danger">Block</a> <a href=""
							class="btn btn-sm btn-info">Post</a></td>
					</tr>
					<tr>
						<td>Jacob</td>
						<td>Thornton</td>
						<td>fat</td>
						<td><a href="" class="btn btn-sm btn-default">Edit</a> <a href=""
							class="btn btn-sm btn-danger">Block</a> <a href=""
							class="btn btn-sm btn-info">Post</a></td>
					</tr>
					<tr>
						<td>Larry</td>
						<td>the Bird</td>
						<td>twitter</td>
						<td><a href="" class="btn btn-sm btn-default">Edit</a> <a href=""
							class="btn btn-sm btn-danger">Block</a> <a href=""
							class="btn btn-sm btn-info">Post</a></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
