<div class="">
	<div class="col-md-12">
		<div class="panel panel-default">
			<!-- Default panel contents -->
			<div class="panel-heading">
				<div class="pull-left">
					<span href="#" class="btn btn-md"><Strong>Candle</Strong></span>
				</div>
				<div class="pull-right">
					<span href="#" class=" btn btn-md btn-success">Add</span>
				</div>
				<div class="clearfix"></div>
			</div>

			<!-- Table -->
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Image</th>
						<th>Title</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Mark</td>
						<td>mdo</td>
						<td><a href="" class="btn btn-sm btn-default">Edit</a></td>
					</tr>
					<tr>
						<td>Jacob</td>
						<td>Thornton</td>
						<td><a href="" class="btn btn-sm btn-default">Edit</a></td>
					</tr>
					<tr>
						<td>Larry</td>
						<td>twitter</td>
						<td><a href="" class="btn btn-sm btn-default">Edit</a></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
