<div class="col-lg-12">
	<div class="col-lg-2 wizard">
		<h3>METER READING</h3>
		<hr>
		<p class="">Its Simple. Select Date/Time, select per unit rate and add
			reading.</p>
		<hr>

	</div>

	<div class="col-lg-10" style="display: none" id="signup-successful">
		<div class="panel">
			<br> <br>
			<h1 class="text text-center text-success">
				<span class="glyphicon glyphicon-thumbs-up"></span>
			</h1>
			<hr>
			<h3 class="text text-center">Brill .. you are successfully registered
				now.</h3>
			<br> <br>
			<p class="text text-center">
				We would like you to <strong class="text text-success">Click a link
					on your Email</strong> which will confirm us that you are a human
				and not a Robot.
			</p>

			<br> <br> <br> <br>
		</div>
	</div>
	<div class="col-lg-10" id="new-reading-wizard">
		<div class="">
			<form class="form-horizontal" ajax-form-submit
				action="<?php echo $this->url("ajax",array("controller"=>"user","action"=>"meter-new-reading"))?>"
				method="post">
				<div class="wizard" data-initialize="wizard" id="new-reading_form">
					<ul class="steps">
						<li data-step="1" data-name="about" class="active">ADD NEW METER
							READING<span class="chevron"></span>
						</li>
						<li class="">Help<span class="chevron"></span></li>
					</ul>
					<div class="step-content">
						<div class="step-pane active sample-pane alert" data-step="1">
							
							<div class="form-group">
								<label for="dtp_input1" class="col-lg-2 control-label">DateTime
								</label>
								<div class="input-group date form_datetime col-lg-5"
									data-date-format="dd MM yyyy - HH:ii p"
									data-link-field="dtp_input1">
									<input class="form-control" id="dated" name="dated" size="16" type="text"
										value="" required readonly> <span class="input-group-addon"><span
										class="glyphicon glyphicon-remove"></span></span> <span
										class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
								</div>
								<input type="hidden" value="" /><br />
							</div>
							<hr>
							<div class="form-group">
								<label class="col-lg-2 control-label">Rate</label>
								<div class="col-lg-10">
									<div class="radio">
										<label> <input type="radio" name="per_unit_rate"
											value="0.20" >&pound;0.20 per unit
										</label>
									</div>
									<div class="radio">
										<label> <input type="radio" name="per_unit_rate"
											value="0.18" >&pound;0.18 per unit

										</label>
									</div>
								</div>

							</div>
							<hr>
							<div class="form-group">
								<label class="col-lg-2 control-label">Meter Reading</label>
								<div class="col-lg-2">
									<input class="form-control" id="reading" name="reading" maxlength="7">
								</div>
							</div>
							<hr>
							<div class="form-group">
								<label class="col-lg-2 control-label"></label>
								<div class="col-lg-2">
									<input type="submit" value="Submit" class="btn btn-primary">
								</div>
							</div>

						</div>

					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<script>
$(function(){

	$('.form_datetime').datetimepicker({
        weekStart: 1,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0,
        showMeridian: 1
    });
    

	// via ajax submit plugin
	$('form[ajax-form-submit]').autosubmit(function(form,response){
		if(response.success){
			showNoty("success",response.message);
			$("#reading").val("");
			$("#dated").val("");
			
		}
		else{
			showNoty("error",response.message);
		}
		
	},function(form,response){
		showNoty("error","Cannot process request. Try Again!");
	});

  
	
});
</script>
