<div class="col-lg-12">
	<div class="col-lg-2 wizard">
		<h3>METER READING</h3>
		<hr>
		<p class="">Its Simple. Select Date/Time, select per unit rate and add
			reading.</p>
		<hr>

	</div>

	<div class="col-lg-10" style="display: none" id="signup-successful">
		<div class="panel">
			<br> <br>
			<h1 class="text text-center text-success">
				<span class="glyphicon glyphicon-thumbs-up"></span>
			</h1>
			<hr>
			<h3 class="text text-center">Brill .. you are successfully registered
				now.</h3>
			<br> <br>
			<p class="text text-center">
				We would like you to <strong class="text text-success">Click a link
					on your Email</strong> which will confirm us that you are a human
				and not a Robot.
			</p>

			<br> <br> <br> <br>
		</div>
	</div>
	<div class="col-lg-10" id="signup-wizard">
		<div class="">
			<form class="form-horizontal" ajax-form-submit
				action="<?php echo $this->url("ajax",array("controller"=>"application","action"=>"signup"))?>"
				method="post">
				<div class="wizard" data-initialize="wizard" id="signup_form">
					<ul class="steps">
						<li data-step="1" data-name="about" class="active">ADD NEW METER
							READING<span class="chevron"></span>
						</li>
						<li class="">Help<span class="chevron"></span></li>
					</ul>
					<div class="step-content">
						<div class="step-pane active sample-pane alert" data-step="1">
							<h5 class="text text-muted">Select Date/Time when you took the
								reading.</h5>
							<hr>

							<div class="form-group">
								<label for="dtp_input1" class="col-lg-2 control-label">DateTime
								</label>
								<div class="input-group date form_datetime col-lg-5"
									data-date-format="dd MM yyyy - HH:ii p"
									data-link-field="dtp_input1">
									<input class="form-control" size="16" type="text" value=""
										required readonly> <span class="input-group-addon"><span
										class="glyphicon glyphicon-remove"></span></span> <span
										class="input-group-addon"><span class="glyphicon glyphicon-th"></span></span>
								</div>
								<input type="hidden" id="dtp_input1" value="" /><br />
							</div>
							<hr>
							<div class="form-group">
								<label class="col-lg-2 control-label">Rate</label>
								<div class="col-lg-10">
									<div class="radio">
										<label> <input type="radio" name="optionsRadios"
											id="optionsRadios1" value="option1" checked="">&pound;0.18
											per unit
										</label>
									</div>
									<div class="radio">
										<label> <input type="radio" name="optionsRadios"
											id="optionsRadios2" value="option2">&pound;0.19 per unit
											&nbsp;&nbsp;&nbsp;&nbsp; <a href="#"><small
												class="btn btn-xs btn-warning">Edit</small></a> <a href="#">
												<small class="btn btn-xs btn-danger">Delete</small>
										</a>
										</label>
									</div>
								</div>
								<div class="col-lg-2"></div>
								<div class="col-lg-10">
								<hr>
									<a href="#" class="btn btn-xs text text-muted pull-left"><span
										class="glyphicon glyphicon-plus"></span> Add More Rates</a>
								</div>
								<div class="clearfix"></div>

							</div>
							<hr>
							<div class="form-group">
								<label class="col-lg-2 control-label">Meter Reading</label>
								<div class="col-lg-2">
									<input class="form-control" maxlength="7">
								</div>
							</div>
							<hr>
							<div class="form-group">
								<label class="col-lg-2 control-label"></label>
								<div class="col-lg-2">
									<input type="submit" value="Submit" class="btn btn-primary">
								</div>
							</div>

						</div>

					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<script>
$(function(){

	$('.form_datetime').datetimepicker({
        weekStart: 1,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0,
        showMeridian: 1
    });
    
	$('#signup_form').on('finished.fu.wizard', function (evt, data) {
		$email = $("#username").val();
		$passwd = $("#passwd").val();
		$c_passwd = $("#c_passwd").val();
		$error = false;
		
		if($email == ""){
			$(".username_error").html("Username is required. Must be a valid email.");
			$error = true;
			
		}
		if($passwd == ""){
			$(".passwd_error").html("Password is required.");
			$error = true;
			
		}
		if($c_passwd == "" || $passwd != $c_passwd){
			$(".c_passwd_error").html("Confirm Passwod is required, and must match Password.");
			$error = true;
		}

		if(!$error)
			$(this).parent().submit();			
		
	});

	// via ajax submit plugin
	$('form[ajax-form-submit]').autosubmit(function(form,response){
		if(response.success){
			showNoty("success",response.message);
			$("#signup-wizard").remove();
			$("#signup-successful").show();
			
		}
		else{
			showNoty("error",response.message);
		}
		
	},function(form,response){
		showNoty("error","Cannot process request. Try Again!");
	});

  
	
});
</script>
