<?php
use Zend\Authentication\AuthenticationService;
echo $this->doctype ();
?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle($this->translate(APP_NAME))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php echo $this->headMeta ()->appendName ( 'viewport', 'width=device-width, initial-scale=1.0' )->appendHttpEquiv ( 'X-UA-Compatible', 'IE=edge' )?>

        <!-- Le styles -->
        <?php		
		$headLink = $this->headLink ( array (
			'rel' => 'shortcut icon',
			'type' => 'image/vnd.microsoft.icon' 
		) );
		$headLink->prependStylesheet ( $this->basePath () . '/css/style.css' );
		$headLink->prependStylesheet ( $this->basePath () . '/css/flat-bootstrap-theme.css' );
		$headLink->prependStylesheet ( "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" );
		$headLink->prependStylesheet("//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css");
		echo $headLink;
		?>
          
        <!--[if IE 7]>
		  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome-ie7.min.css">
		<![endif]-->
		
		<link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
		<!-- Scripts -->
        
        <?php
		$headScript = $this->headScript ();
		$headScript->prependFile ( $this->basePath () . '/js/noty/packaged/jquery.noty.packaged.min.js' );
		$headScript->prependFile ( "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js" );
		$headScript->prependFile ( "//code.jquery.com/jquery-1.11.3.min.js" );
		$headScript->prependFile ( $this->basePath () . '/js/respond.min.js', 'text/javascript', array (
			'conditional' => 'lt IE 9' 
		));
		$headScript->prependFile ( $this->basePath () . '/js/html5shiv.js', 'text/javascript', array (
			'conditional' => 'lt IE 9' 
		));
		echo $headScript;
		?>

</head>

<style>
.brand-one,.brand-two{
font-family: 'Indie Flower', cursive;
font-size:32px;
}
.brand-one{
color:#16A085;
}
.brand-two{
color:#2980B9;
}		
</style>

<body>
<?php
// get service locator
$sl = $this->viewmodel ()->getView ()->getHelperPluginManager ()->getServiceLocator ();

// $UserTable = $sl->get('Model\Entity\User');
$Auth = new AuthenticationService ();
// check has identity, else Tests cases will fail
if ($Auth->hasIdentity ()) {
	$AuthStorage = $Auth->getStorage ()->read ();
	//echo $AuthStorage->username;
}

?>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<?php echo $this->url('home') ?>">&nbsp;<span class="brand-one">Save</span>
				<span class="brand-two">Energy</span>	</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
				<?php if($Auth->hasIdentity()){?>
			     	<li class="active"><a
						href="<?php echo $this->url('user',array('controller'=>'dashboard','action'=>'index')) ?>"><span
							class='glyphicon glyphicon-dashboard'></span> <?php echo $this->translate('Dashboard') ?></a></li>
			     	<li class="active"><a
						href="<?php echo $this->url('user',array('controller'=>'meter','action'=>'get-stats')) ?>"><span
							class='glyphicon glyphicon-user'></span> <?php echo $this->translate('Stats') ?></a></li>
			     	<li class="active"><a
						href="<?php echo $this->url('user',array('controller'=>'meter','action'=>'new-reading')) ?>"><span
							class='glyphicon glyphicon-user'></span> <?php echo $this->translate('New Reading') ?></a></li>
					<li class="active"><a
						href="<?php echo $this->url('application/child',array('controller'=>'signin','action'=>'quit')) ?>"><span
							class='glyphicon glyphicon-log-out'></span> <?php echo $this->translate('Sign Out') ?></a></li>
					<?php } else {?>
					<li class="active"><a
						href="<?php echo $this->url('application/child',array('controller'=>'signin','action'=>'index')) ?>"><span
							class='glyphicon glyphicon-log-in'></span> <?php echo $this->translate('Sign In') ?></a></li>
					<li class="active"><a
						href="<?php echo $this->url('application/child',array('controller'=>'signup','action'=>'index')) ?>"><span
							class='glyphicon glyphicon-user'></span> <?php echo $this->translate('Sign Up') ?></a></li>
					<?php } ?>
				</ul>
			</div>
			<!--/.nav-collapse -->
		</div>
	</nav>
	<div class="container-fluid">
		<div class='row'>
			<div class='col-md-12'>
                <?php echo $this->partial('flash-messages'); ?>
                    
    	        <?php echo $this->layout()->content; ?>
	        </div>
		</div>
		<div class='row'>
			<div class='col-md-12 '>
				<hr>
				<footer>
					<br>
					<br>
					<p>&copy; <?php echo date('Y') ?>. <?php echo $this->translate('All rights reserved.')?>
					<small class='pull-right'><a href='<?php echo PROJECT_WEBSITE?>'><?php echo PROJECT_WEBSITE?></a></small>
					</p>
					<br>
					<br>
					<br>
					<br>
				</footer>
			</div>
		</div>
	</div>
	<!-- /container -->
    <?php echo $this->inlineScript()?>
    </body>
</html>
