<h1></h1>
<div class="col-lg-12">
	<div class="col-lg-2 panel">
		<h3>SIGN UP</h3>
		<hr>
		<p class="lead text text-muted">Registration is straight forward.
			Please select the Provider you currently have and give us your basic
			information.</p>
		<p class="text text-default">
			Already have an account <a
				href="<?php echo $this->url("application/child",array("controller"=>"signup"))?>">Click
				Here</a> to Sign in.
		</p>

		<small class="text text-muted">We will never send you promotional
			email, unless you subscribe with us.</small> <br> <br>
	</div>

	<div class="col-lg-10">
		<div class="">
			<div class="panel-body">
				<form class="form-horizontal"
					action="<?php echo $this->url("application/child",array("controller"=>"signin","action"=>"process"))?>"
					method="post">
					<div class="wizard" data-initialize="wizard" id="myWizard">
						<ul class="steps">
							<li data-step="1" data-name="campaign" class="active"><span
								class="badge">1</span>Provider<span class="chevron"></span></li>
							<li data-step="2"><span class="badge">2</span>Address<span
								class="chevron"></span></li>
							<li data-step="3" data-name="template"><span class="badge">3</span>Login
								Info<span class="chevron"></span></li>
						</ul>
						<div class="actions">
							<button type="button" class="btn btn-primary btn-sm btn-prev">
								<span class="glyphicon glyphicon-arrow-left"></span>Prev
							</button>
							<button type="button" class="btn btn-primary btn-next btn-sm"
								data-last="Complete">
								Next<span class="glyphicon glyphicon-arrow-right"></span>
							</button>
						</div>
						<div class="step-content">
							<div class="step-pane active sample-pane alert" data-step="1">
								<h5 CLASS="text text-muted">SELECT YOUR ELECTRICITY PROVIDER</h5>
								<hr>
								<div class="form-group">
									<div class="col-lg-12">
										<h4>
										<div class="radio">
											<label> <input type="radio" name="optionsRadios"
												id="optionsRadios1" value="option1" checked=""> Spark Energy
												<br><small>dede dede</small>
											</label>
										</div>
										<div class="radio">
											<label> <input type="radio" name="optionsRadios"
												id="optionsRadios2" value="option2"> 
											</label>
										</div>
										</h4>
									</div>
								</div>

							</div>
							<div class="step-pane sample-pane " data-step="2">
								<h4>Choose Recipients</h4>
								<p>Celery quandong swiss chard chicory earthnut pea potato.
									Salsify taro catsear garlic gram celery bitterleaf wattle seed
									collard greens nori. Grape wattle seed kombu beetroot
									horseradish carrot squash brussels sprout chard.</p>
							</div>
							<div class="step-pane sample-pane" data-step="3">
								<h4>Design Template</h4>
								<p>Nori grape silver beet broccoli kombu beet greens fava bean
									potato quandong celery. Bunya nuts black-eyed pea prairie
									turnip leek lentil turnip greens parsnip. Sea lettuce lettuce
									water chestnut eggplant winter purslane fennel azuki bean
									earthnut pea sierra leone bologi leek soko chicory celtuce
									parsley jícama salsify.</p>
							</div>
						</div>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>

