<h1></h1>
<div class="col-lg-12">
	<div class="col-lg-2 panel">
		<h3>SIGN UP</h3>
		<hr>
		<p class="lead text text-muted">Registration is straight forward.
			Please select the Provider you currently have and give us your basic
			information.</p>
		<p class="text text-default">
			Already have an account <a
				href="<?php echo $this->url("application/child",array("controller"=>"signup"))?>">Click
				Here</a> to Sign in.
		</p>

		<small class="text text-muted">We will never send you promotional
			email, unless you subscribe with us.</small> <br> <br>
	</div>

	<div class="col-lg-10">
		<div class="">
			<div class="panel-body">
				<form class="form-horizontal"
					action="<?php echo $this->url("application/child",array("controller"=>"signin","action"=>"process"))?>"
					method="post">
					<div class="wizard" data-initialize="wizard" id="myWizard">
						<ul class="steps">
							<li data-step="1" data-name="campaign" class="active"><span
								class="badge">1</span>About You<span class="chevron"></span></li>
							<li data-step="2"><span class="badge">2</span>Basic Settings<span
								class="chevron"></span></li>
							<li data-step="3" data-name="template"><span class="badge">3</span>Login
								Details<span class="chevron"></span></li>
						</ul>
						<div class="actions">
							<button type="button" class="btn btn-primary btn-sm btn-prev">
								<span class="glyphicon glyphicon-arrow-left"></span>Prev
							</button>
							<button type="button" class="btn btn-primary btn-next btn-sm"
								data-last="Complete">
								Next<span class="glyphicon glyphicon-arrow-right"></span>
							</button>
						</div>
						<div class="step-content">
							<div class="step-pane active sample-pane alert" data-step="1">
								<h5 class="text text-muted">Below information will help us to
									identify you.</h5>
								<hr>
								<div class="form-group">
									<label for="inputEmail" class="col-lg-2 control-label">First
										Name</label>
									<div class="col-lg-10">
										<input type="text" class="form-control" id="first_name"
											name="first_name" placeholder="(this is optional)">
									</div>
								</div>
								<div class="form-group">
									<label for="inputEmail" class="col-lg-2 control-label">Last
										Name</label>
									<div class="col-lg-10">
										<input type="text" class="form-control" id="last_name"
											name="last_name" placeholder="(this is optional)">
									</div>
								</div>

								<div class="form-group">
									<label for="inputEmail" class="col-lg-2 control-label">Mobile</label>
									<div class="col-lg-10">
										<input type="text" class="form-control" id="mobile"
											name="mobile" placeholder="(this is optional)">
									</div>
								</div>


							</div>
							<div class="step-pane sample-pane alert " data-step="2">
								<h5 class="text text-muted">Below settings will help you to
									receive alert email and updates.</h5>
								<hr>
								<div class="form-group">
									<label for="inputEmail" class="col-lg-2 control-label">Weekly
										Cost Threshold</label>
									<div class="col-lg-10">
										<input type="text" class="form-control"
											id="weekly_cost_threshold" name="weekly_cost_threshold"
											placeholder="(this is optional)"> <small>if your Weekly cost
											reach to specify amount, we will send you alert email</small>
									</div>
								</div>
								<div class="form-group">
									<label for="inputEmail" class="col-lg-2 control-label">Monthly
										Cost Threshold</label>
									<div class="col-lg-10">
										<input type="text" class="form-control"
											id="monthly_cost_threshold" name="monthly_cost_threshold"
											placeholder="(this is optional)"> <small>if your Monthly cost
											reach to specify amount, we will send you alert email</small>
									</div>
								</div>
								<div class="form-group">
									<label for="inputEmail" class="col-lg-2 control-label">Quarterly
										Cost Threshold</label>
									<div class="col-lg-10">
										<input type="text" class="form-control"
											id="quarterly_cost_threshold" name="quarterly_cost_threshold"
											placeholder="(this is optional)"> <small>if your Quarterly
											cost reach to specify amount, we will send you alert email</small>
									</div>
								</div>

							</div>
							<div class="step-pane sample-pane alert" data-step="3">
								<h5 class="text text-muted">Below information will let you login.</h5>
								<hr>

								<div class="form-group">
									<label for="inputEmail" class="col-lg-2 control-label">Email</label>
									<div class="col-lg-10">
										<input type="email" class="form-control" id="email"
											name="email" placeholder="(this is REQUIRED)">
									</div>
								</div>
								<div class="form-group">
									<label for="inputEmail" class="col-lg-2 control-label">Password</label>
									<div class="col-lg-10">
										<input type="password" class="form-control" id="passwd"
											name="passwd" placeholder="(this is REQUIRED)">
									</div>
								</div>
								<div class="form-group">
									<label for="inputEmail" class="col-lg-2 control-label">Confirm Password</label>
									<div class="col-lg-10">
										<input type="password" class="form-control" id="c_passwd"
											name="c_passwd" placeholder="(this is REQUIRED)">
									</div>
								</div>
								
							</div>
						</div>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>

